import { StyleSheet, Dimensions } from 'react-native';
import { SW, SH, SF, ShadowStyles } from '@/theme';
import { COLORS } from '@/theme';
import { Fonts } from '@/assets';
import { verticalScale, moderateScale, ms } from 'react-native-size-matters';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  displayFlex: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexAlign: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calenderContainer: {
    width: windowWidth * 0.94,
  },
  headerMainView: {
    width: windowWidth,
    paddingHorizontal: SW(16),
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingTop: SH(13),
    flexDirection: 'row',
  },
  textInputStyle: {
    width: SW(45),
    marginLeft: 10,
    fontFamily: Fonts.Italic,
    fontSize: SF(15),
  },
  truckStyle: {
    width: SH(32),
    height: SH(32),
    resizeMode: 'contain',
  },
  deliveryView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deliveryText: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.solid_grey,
    fontSize: SF(18),
    paddingLeft: SW(4),
  },
  searchView: {
    borderWidth: 1,
    width: SW(65),
    height: SH(40),
    borderRadius: SH(23),
    borderColor: COLORS.row_grey,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchImage: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    left: 3,
  },
  calenderCon: {
    width: windowWidth * 0.84,
    height: windowHeight * 0.904,
  },
  notificationCon: {
    width: windowWidth * 0.3,
    height: '90%',
    position: 'absolute',
    top: ms(40),
    right: 110,
    backgroundColor: COLORS.white,
  },
  approveButtonCon: {
    backgroundColor: COLORS.primary,
    borderRadius: 3,
    height: SH(32),
    width: SH(110),
    justifyContent: 'center',
    alignItems: 'center',
  },
  noButtonCon: {
    backgroundColor: COLORS.dark_grey,
    borderRadius: 3,
    height: SH(32),
    justifyContent: 'center',
    alignItems: 'center',
    width: SH(110),
    marginLeft: moderateScale(10),
  },

  approveText: {
    color: COLORS.white,
    fontSize: SF(12),
    fontFamily: Fonts.Regular,
  },
  requestFor: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(15),
    width: windowWidth * 0.25,
    overflow: 'hidden',
  },
  timeLabel: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(15),
    paddingHorizontal: moderateScale(5),
  },
  notificationchildCon: {
    borderBottomWidth: 1,
    borderColor: '#F3F3F3',
    paddingHorizontal: moderateScale(8),
    paddingVertical: verticalScale(8),
  },
  roundCalender: {
    width: SH(22),
    height: SH(22),
    resizeMode: 'contain',
    tintColor: COLORS.bluish_green,
  },
  watch: {
    width: SH(18),
    height: SH(18),
    resizeMode: 'contain',
    tintColor: COLORS.bluish_green,
  },
  modalMainView: {
    backgroundColor: COLORS.white,
    width: SW(180),
    borderRadius: 12,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  headerView: {
    backgroundColor: COLORS.primary,
    width: SW(180),
    height: SH(60),
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  crossIconStyle: {
    width: SH(24),
    height: SH(24),
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  trackingButtonText: {
    fontFamily: Fonts.Medium,
    color: COLORS.white,
    fontSize: SF(12),
  },
  charlene: {
    width: SH(100),
    height: SH(100),
    resizeMode: 'contain',
    borderRadius: 100,
  },
  address: {
    fontFamily: Fonts.Regular,
    color: COLORS.darkGray,
    fontSize: SF(14),
    paddingHorizontal: moderateScale(5),
  },
  charleneName: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: SF(20),
  },
  location: {
    width: SH(16),
    height: SH(16),
    resizeMode: 'contain',
  },
  appointment: {
    fontFamily: Fonts.MaisonRegular,
    color: COLORS.primary,
    fontSize: SF(18),
  },
  service: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.dark_grey,
    fontSize: SF(16),
  },
  serviceType: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(14),
    marginRight: moderateScale(10),
  },
  upcomingCon: {
    borderRadius: 3,
    backgroundColor: COLORS.bluish_green,
    height: SH(35),
    width: SH(116),
    justifyContent: 'center',
    alignItems: 'center',
  },
  upcomingText: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.white,
    fontSize: SF(16),
  },
  calenderHeader: {
    height: SH(60),
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    paddingLeft: moderateScale(5),
  },
  unChecked: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(12),
    // paddingHorizontal:moderateScale(18)
  },
  clickedButtonCon: {
    backgroundColor: COLORS.primary,
    height: SH(32),
    width: SH(68),
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: moderateScale(10),
  },
  unClickedButtonCon: {
    backgroundColor: COLORS.textInputBackground,
    height: SH(32),
    width: SH(68),
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: moderateScale(10),
  },
  checkedText: {
    fontFamily: Fonts.Regular,
    color: COLORS.white,
    fontSize: SF(12),
  },
  unCheckedText: {
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
    fontSize: SF(12),
  },
  schdule: {
    height: SH(670),
    width: windowWidth * 0.68,
    resizeMode: 'contain',
  },
  monthlySchduel: {
    height: SH(36),
    // width: SH(240),
    backgroundColor: COLORS.white,
    borderRadius: 3,
    paddingHorizontal: moderateScale(5),
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftLight: {
    width: SH(20),
    height: SH(20),
    resizeMode: 'contain',
  },
  monthlySchduleDate: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.dark_grey,
    fontSize: SF(14),
    paddingHorizontal: moderateScale(5),
  },
  headerBody: {
    width: SW(170),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(10),
  },
  startEndDate: {
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
    fontSize: SH(11),
  },
  eventContainer: {
    backgroundColor: 'white',
    elevation: 0,
    borderColor: COLORS.primary,
    borderLeftColor: COLORS.primary,
    borderLeftWidth: ms(2),
    borderStyle: 'solid',
    borderRadius: ms(1),
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventTitle: {
    color: COLORS.primary,
    fontFamily: Fonts.Bold,
    fontSize: SH(11),
  },
  iImageCon: {
    backgroundColor: COLORS.dark_grey,
    borderRadius: 100,
    height: SW(8),
    justifyContent: 'center',
    alignItems: 'center',
    width: SW(8),
  },
  iImage: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    tintColor: COLORS.white,
  },
  serviceTextCon: {
    flexDirection: 'row',
    width: windowWidth * 0.45,
  },
  requestTextName: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.black,
    width: windowWidth * 0.5,
  },
  lockLight: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    paddingLeft: moderateScale(5),
  },
  requestNotFound: {
    fontFamily: Fonts.Regular,
    color: COLORS.primary,
    alignSelf: 'center',
    marginTop: 50,
    fontSize: SF(20),
  },
  arrowButtonStl: {
    backgroundColor: COLORS.textInputBackground,
    borderRadius: ms(2),
    paddingHorizontal: ms(3),
    paddingVertical: ms(2),
  },
  rightTabContainer: {
    backgroundColor: COLORS.textInputBackground,
    flex: 0.9,
    margin: ms(7),
    marginLeft: ms(10),
    marginTop: ms(10),
    height: '97.8%',
    alignItems: 'center',
  },
  RequestEventBadgeText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    color: COLORS.white,
  },
  requestEventBadgeContainer: {
    height: ms(10),
    width: ms(10),
    borderRadius: ms(5),
    backgroundColor: COLORS.yellowTweet,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  requestCalendarIcon: { height: ms(20), width: ms(20), resizeMode: 'contain' },
  requestCalendarContainer: {
    backgroundColor: COLORS.white,
    height: ms(35),
    width: '80%',
    marginTop: ms(5),
    borderRadius: ms(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeTextEmployee: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(4),
    color: COLORS.black,
  },
  circularBadgeEmployee: {
    position: 'absolute',
    right: -6,
    bottom: -5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: 'teal',
    height: ms(10),
    width: ms(10),
    borderRadius: ms(5),
  },
  employeeImages: {
    height: '100%',
    width: '100%',
    borderRadius: ms(8),
    resizeMode: 'cover',
  },
  renderItemContainer: {
    borderColor: COLORS.yellowTweet,
    borderWidth: 2,
    height: ms(19),
    width: ms(19),
    borderRadius: ms(9.5),
    alignItems: 'center',
    justifyContent: 'center',
    margin: ms(5),
  },
  asigneesBadgeText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    color: COLORS.dark_grey,
  },
  circularBadgeContainer: {
    height: ms(10),
    width: ms(10),
    borderRadius: ms(5),
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.dark_grey,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: -8,
    bottom: -6,
  },
  asignessCalendarImage: {
    height: ms(14),
    width: ms(14),
    resizeMode: 'contain',
  },
  alignmentCalendarContainer: { alignSelf: 'center', marginVertical: ms(10) },
  calendarIconSettings: {
    height: ms(20),
    width: ms(20),
    resizeMode: 'contain',
  },
  CalendarSettingsContainer: {
    position: 'absolute',
    height: ms(40),
    width: '95%',
    alignSelf: 'center',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
