import { Fonts } from '@/assets';
import { COLORS, SF, SH, SW } from '@/theme';
import { height, width } from '@/theme/ScalerDimensions';
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { moderateScale, verticalScale, ms } from 'react-native-size-matters';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.textInputBackground,
  },

  displayflex: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  displayflex2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  // main screen css start
  homeScreenCon: {
    flex: 1,
    backgroundColor: COLORS.textInputBackground,
    paddingHorizontal:
      Platform.OS === 'android' ? moderateScale(12) : moderateScale(12),
  },
  searchScreenHeader: {
    height: SH(60),
    justifyContent: 'center',
  },
  cashLabelBold: {
    color: COLORS.solid_grey,
    fontSize: SF(12),
    fontFamily: Fonts.Medium,
  },
  crossBg: {
    width: SW(10),
    height: SW(8),
    resizeMode: 'contain',
  },
  _centerContainer: {
    backgroundColor: COLORS.white,
    // marginTop: ms(20),
    // marginHorizontal: ms(26),
    marginBottom: ms(10),
    borderRadius: ms(3),
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  _totalAmountTitle: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(20),
  },
  _dollarSymbol: {
    fontSize: ms(20),
    color: COLORS.primary,
    fontFamily: Fonts.SemiBold,
    marginTop: ms(2),
  },
  _dollarInput: {
    fontSize: ms(10),
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    marginBottom: ms(1),
  },
  _amount: {
    color: COLORS.primary,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(30),
  },
  _bottomContainer: {
    marginTop: ms(10),
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    borderRadius: ms(8),
  },
  _selectTips: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(12),
    color: COLORS.solid_grey,
  },
  _boxView: {
    height: ms(110),
    width: ms(118),
    backgroundColor: COLORS.transparentBlue,
    borderRadius: ms(8),
    justifyContent: 'center',
    alignItems: 'center',
    margin: ms(5),
    borderWidth: 1,
  },
  _usdText: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
  },
  _tipsPercent: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    marginTop: ms(2),
  },
  _innerContainer: {
    backgroundColor: COLORS.textInputBackground,
    flex: 1,
    paddingHorizontal: moderateScale(12),
  },
  _inputMain: {
    marginTop: ms(15),
    width: '98%',
  },
  _inputSubView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  _inputContainer: {
    height: ms(40),
    borderRadius: ms(3),
    flex: 1,
  },
  dollarInputCon: {
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    height: ms(40),
    borderRadius: ms(3),
    paddingHorizontal: ms(10),
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  _inputCashContainer: {
    height: ms(40),
    borderRadius: ms(3),
    borderWidth: 1,
    paddingHorizontal: ms(10),
    borderColor: COLORS.solidGrey,
    flex: 1,
  },
  _tipsButton: {
    height: ms(40),
    paddingHorizontal: ms(10),
    backgroundColor: COLORS.silver_solid,
    borderRadius: ms(3),
    justifyContent: 'center',
    alignContent: 'center',
    flex: 0.4,
    marginLeft: ms(10),
  },
  _tipText: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    alignSelf: 'center',
  },
  _border: {
    height: ms(10),
    backgroundColor: COLORS.solidGrey,
    width: ms(1),
    marginHorizontal: ms(10),
  },
  _date: {
    color: COLORS.black,
    fontFamily: Fonts.Regular,
    fontSize: ms(8),
  },
  _topContainer: {
    position: 'absolute',
    marginLeft: ms(25),
    width: '98%',
    alignItems: 'center',
    height: ms(30),
    flexDirection: 'row',
  },
  _cross: {
    height: ms(15),
    width: ms(15),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: ms(20),
  },
  _payBYBoxContainer: {
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    height: ms(110),
    width: ms(170),
    margin: ms(3),
    borderRadius: ms(6),
    justifyContent: 'center',
    alignItems: 'center',
  },
  _payByTitle: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: ms(9),
    marginBottom: ms(5),
  },
  _payByMethod: {
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
    fontSize: ms(14),
    marginTop: ms(4),
  },
  _payByAmount: {
    fontFamily: Fonts.Regular,
    color: COLORS.solid_grey,
    fontSize: ms(10),
    marginTop: ms(4),
  },
  _payByIcon: {
    height: ms(22),
    width: ms(22),
    resizeMode: 'contain',
    marginTop: ms(8),
  },
  _bottomCardView: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.primary,
    height: ms(110),
    width: ms(160),
    borderRadius: ms(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  _cardIconView: {
    height: ms(47),
    width: ms(47),
    tintColor: COLORS.solid_green,
  },
  _cardSubtitle: {
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    color: COLORS.white,
    marginTop: ms(12),
  },
  _sendRequest: {
    height: ms(40),
    paddingHorizontal: ms(10),
    backgroundColor: COLORS.dark_grey,
    borderRadius: ms(3),
    justifyContent: 'center',
    alignContent: 'center',
    flex: 0.4,
    marginLeft: ms(10),
  },
  _orContainer: {
    flexDirection: 'row',
    marginVertical: ms(5),
    alignItems: 'center',
  },
  _borderView: {
    backgroundColor: COLORS.solidGrey,
    height: 1,
    flex: 1,
  },
  _orText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(6),
    marginHorizontal: ms(7),
  },
  _sendPaymentText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(8),
    color: COLORS.solid_grey,
    marginBottom: ms(10),
    marginTop: ms(20),
  },
  itemLIistCon: {
    width: windowWidth * 0.65,
    height: windowHeight * 0.88,
    backgroundColor: COLORS.white,
    borderRadius: 10,
    paddingHorizontal: moderateScale(8),
    paddingTop: verticalScale(8),
  },
  rightSideCon: {
    width: windowWidth * 0.26,
    height: windowHeight * 0.87,
    paddingHorizontal: moderateScale(4),
    paddingBottom: verticalScale(4),
    // backgroundColor: COLORS.white,
    // backgroundColor: COLORS.textInputBackground,
  },
  chooseCategoryCon: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    width: windowWidth * 0.2,
    height: SH(45),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(8),
  },
  categoryMenu: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
  },
  chooseCat: {
    color: COLORS.black,
    fontSize: SF(13),
    fontFamily: Fonts.Medium,
    width: windowWidth * 0.16,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: SW(2),
  },
  barcodeInputWraper: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 7,
    width: windowWidth * 0.41,
    height: SH(45),
    marginRight: 8,
    justifyContent: 'center',
  },
  allProduct: {
    color: COLORS.solid_grey,
    fontSize: SF(13),
    fontFamily: Fonts.Medium,
  },
  allProductCount: {
    color: COLORS.darkGray,
    fontSize: SF(13),
    fontFamily: Fonts.Italic,
  },
  productBodyCon: {
    backgroundColor: COLORS.textInputBackground,
    // flex: 1,
    borderRadius: 10,
    // paddingTop: verticalScale(5),
    paddingHorizontal: moderateScale(4),
  },
  productCon: {
    width: Platform.OS === 'ios' ? windowWidth * 0.115 : windowWidth * 0.117,
    height: Platform.OS === 'ios' ? windowHeight * 0.22 : windowHeight * 0.24,
    backgroundColor: COLORS.white,
    borderRadius: 5,
    paddingHorizontal: moderateScale(3),
    paddingBottom: verticalScale(5),
    marginTop: verticalScale(5),
    marginLeft: 6,
  },
  categoryshoes: {
    width: windowWidth * 0.117,
    height: windowHeight * 0.11,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  productDes: {
    color: COLORS.black,
    fontSize: SF(11),
    fontFamily: Fonts.Medium,
  },
  productSubHead: {
    color: COLORS.darkGray,
    fontSize: SF(11),
    fontFamily: Fonts.Italic,
  },
  productPrice: {
    color: COLORS.black,
    fontSize: SF(15),
    fontFamily: Fonts.SemiBold,
  },

  // sideBar css start
  keyboard: {
    width: SW(12),
    height: Platform.OS === 'android' ? SH(38) : SH(45),
    resizeMode: 'contain',
  },
  holdCartCon: {
    width: windowWidth * 0.1,
    height: SH(38),
    borderRadius: 5,
    backgroundColor: COLORS.marshmallow,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pause: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
  },
  holdCart: {
    color: COLORS.white,
    fontSize: SF(12),
    fontFamily: Fonts.Bold,
    paddingHorizontal: moderateScale(3),
  },

  dark_greyBg: {
    backgroundColor: COLORS.dark_grey,
  },
  addNotesBtn: {
    backgroundColor: COLORS.primary,
    alignSelf: 'flex-end',
  },
  nameAddCon: {
    borderWidth: 1,
    height:
      Platform.OS === 'android' ? windowHeight * 0.35 : windowHeight * 0.37,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    paddingHorizontal: moderateScale(5),
  },
  sideBarInputWraper: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    alignItems: 'center',
    height: Platform.OS === 'android' ? SH(40) : SH(45),
    justifyContent: 'center',
    marginTop: 5,
    paddingLeft: moderateScale(22),
    backgroundColor: COLORS.white,
  },
  sideSearchStyle: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    marginLeft: moderateScale(10),
    marginRight: moderateScale(5),
    tintColor: COLORS.gerySkies,
  },
  sideBarsearchInput: {
    borderRadius: 7,
    width: windowWidth * 0.24,
    fontFamily: Fonts.Italic,
    fontSize: SF(12),
    color: COLORS.solid_grey,
    height: SH(40),
    flex: 1,
  },
  nameAddSingleCon: {
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    justifyContent: 'center',
    height: Platform.OS === 'android' ? SH(40) : SH(45),
    backgroundColor: COLORS.textInputBackground,
    marginTop: 5,
  },
  Phonelight: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    tintColor: COLORS.darkGray,
    marginLeft: moderateScale(10),
    marginRight: moderateScale(5),
  },
  terryText: {
    color: COLORS.solid_grey,
    fontSize: SF(14),
    fontFamily: Fonts.Regular,
  },
  lockLight: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(10),
  },
  okButtonCon: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    borderColor: COLORS.dark_grey,
    width: windowWidth * 0.24,
    alignSelf: 'center',
    borderRadius: 5,
    height: Platform.OS === 'android' ? SH(40) : SH(45),
    marginTop: 5,
  },
  okText: {
    color: COLORS.white,
    fontSize: SF(14),
    fontFamily: Fonts.SemiBold,
  },
  addDiscountCon: {
    backgroundColor: COLORS.blue_shade,
    height: Platform.OS === 'android' ? SH(40) : SH(45),
    width: windowWidth * 0.12,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(3),
  },
  addDiscountText: {
    color: COLORS.dark_grey,
    fontSize: SF(12),
    fontFamily: Fonts.MaisonRegular,
  },
  addDiscountPic: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(7),
  },
  totalItemCon: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
    paddingVertical: verticalScale(3),
  },
  totalItem: {
    fontSize: SF(16),
    color: COLORS.primary,
    fontFamily: Fonts.MaisonBold,
    paddingVertical: verticalScale(4),
  },
  paddVertical: {
    paddingVertical: verticalScale(3),
  },
  subTotal: {
    fontSize: SF(14),
    color: COLORS.dark_grey,
    fontFamily: Fonts.MaisonBold,
  },
  subTotalDollar: {
    fontSize: SF(14),
    color: COLORS.black,
    fontFamily: Fonts.Regular,
  },
  itemValue: {
    fontSize: SF(16),
    color: COLORS.solid_grey,
    fontFamily: Fonts.MaisonBold,
  },
  itemValueBold: {
    fontFamily: Fonts.SemiBold,
  },
  checkoutButtonSideBar: {
    width: windowWidth * 0.25,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    alignSelf: 'center',
    borderRadius: 5,
    paddingVertical: verticalScale(7),
  },
  checkoutText: {
    color: COLORS.white,
    fontSize: SF(16),
    fontFamily: Fonts.SemiBold,
  },
  checkArrow: {
    width: SW(10),
    height: SW(4),
    resizeMode: 'contain',
    paddingHorizontal: moderateScale(6),
  },

  // sideBar css end

  // categoryModal css Start
  categoryModalCon: {
    backgroundColor: COLORS.white,
    width: windowWidth * 0.55,
    height: windowHeight * 0.75,
    borderRadius: 10,
    alignSelf: 'center',
    paddingHorizontal: moderateScale(10),
  },
  crossButton: {
    width: SW(9),
    height: SW(9),
    resizeMode: 'contain',
  },
  categories: {
    color: COLORS.dark_grey,
    fontSize: SF(17),
    fontFamily: Fonts.SemiBold,
  },
  categoryInputWraper: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    height: Platform.OS === 'android' ? SH(48) : SH(45),
  },
  catProArrayCon: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    width: windowWidth * 0.123,
    justifyContent: 'center',
    paddingHorizontal: moderateScale(10),
    marginTop: verticalScale(5),
    marginRight: moderateScale(7),
    paddingVertical: SH(5),
  },
  cloth: {
    width: SW(14),
    height: SW(14),
    resizeMode: 'contain',
  },
  categories: {
    color: COLORS.black,
    fontSize: SF(16),
    fontFamily: Fonts.MaisonBold,
  },
  listed: {
    color: COLORS.darkGray,
    fontSize: SF(11),
    fontFamily: Fonts.Regular,
  },
  categoryflatlistHeight: {
    height: windowHeight * 0.58,
  },

  // categoryModal css end

  // addto cart modal css start
  addCartCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.5,
    height: windowHeight * 0.9,
    position: 'absolute',
    alignSelf: 'center',
  },

  addCartConHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: SH(70),
    paddingHorizontal: moderateScale(15),
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  backTocartCon: {
    backgroundColor: '#F5F6F7',
    width: SH(130),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
  },
  backTocartText: {
    color: COLORS.black,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  continueBtnCon: {
    width: SH(120),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.primary,
    borderWidth: 1,
    marginLeft: SH(10),
    borderRadius: 3,
  },
  addToCartCon: {
    backgroundColor: COLORS.primary,
    width: SH(120),
    height: SH(44),
    padding: SH(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: SH(10),
    borderRadius: 3,
  },
  addTocartText: {
    color: COLORS.white,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },
  colimbiaText: {
    color: COLORS.black,
    fontSize: SH(20),
    fontFamily: Fonts.Bold,
  },
  detailLeftDetail: {
    width: windowWidth * 0.35,
  },
  sizeAndColor: {
    color: COLORS.dark_grey,
    fontSize: SH(16),
    fontFamily: Fonts.Medium,
  },
  counterCon: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginVertical: SH(20),
  },
  minusBtnCon: {
    borderColor: '#D8D8D8',
    borderWidth: 1,
    width: windowWidth * 0.14,
    height: SH(60),
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    fontSize: SH(28),
    fontFamily: Fonts.Bold,
    color: COLORS.black,
  },
  colorText: {
    marginHorizontal: SH(10),
    fontSize: SH(18),
    fontFamily: Fonts.Regular,
    color: COLORS.gerySkies,
  },
  colorRow: {
    height: SH(2),
    // width: SH(235),
    width: windowWidth * 0.17,
    backgroundColor: '#D8D8D8',
  },
  selectColorItem: {
    width: SH(142),
    height: SH(60),
    borderRadius: 5,
    borderColor: '#E1E3E4',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginHorizontal: moderateScale(3),
  },
  colorSelectText: {
    fontSize: SF(18),
    fontFamily: Fonts.Regular,
    color: COLORS.black,
  },
  detailBtnCon: {
    color: COLORS.primary,
    fontSize: SH(13),
    fontFamily: Fonts.SemiBold,
  },

  // addto cart modal css end

  // addto cart detail modal css start
  addCartDetailConHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: SH(70),
  },
  addCartDetailConHeader2: {
    height: SH(55),
    borderBottomWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  addCartDetailCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.6,
    height: windowHeight * 0.92,
    position: 'absolute',
    alignSelf: 'center',
    paddingHorizontal: moderateScale(13),
  },
  jacketName: {
    color: COLORS.solid_grey,
    fontSize: SH(18),
    fontFamily: Fonts.SemiBold,
  },
  addCartDetailBody: {
    height: windowHeight * 0.82,
  },
  clothProfileCon: {
    height: windowHeight * 0.08,
    flexDirection: 'row',
  },
  clothProfileDes: {
    color: COLORS.darkGray,
    fontSize: SH(11),
    fontFamily: Fonts.Regular,
  },
  clothProfileSubHead: {
    color: COLORS.darkGray,
    fontSize: SH(11),
    fontFamily: Fonts.Italic,
  },
  profileCloth: {
    width: SW(16),
    height: SW(16),
    resizeMode: 'contain',
  },
  profileClothDes: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginLeft: 10,
  },
  priceCon: {
    height: windowHeight * 0.07,
    backgroundColor: COLORS.washGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(10),
    alignItems: 'center',
  },
  skuCon: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 7,
    paddingHorizontal: moderateScale(7),
  },
  skuConBody: {
    height: windowHeight * 0.06,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderColor: COLORS.solidGrey,
  },
  reOrderBody: {
    height: windowHeight * 0.05,
    borderTopWidth: 1,
    borderBottomWidth: 0,
  },
  sku: {
    color: COLORS.solid_grey,
    fontSize: SH(14),
    fontFamily: Fonts.Regular,
  },
  inStoreBody: {
    height: windowHeight * 0.06,
    borderWidth: 1,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderColor: COLORS.solidGrey,
    paddingHorizontal: moderateScale(15),
  },
  inStoreText: {
    color: COLORS.solid_grey,
    fontSize: SH(14),
    fontFamily: Fonts.MaisonBold,
  },
  toggleSecBlue: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
  },
  ScrollableMainCon: {
    width: windowWidth * 0.48,
    alignSelf: 'center',
    // borderWidth: 1,

    // height: windowHeight * 0.5,
  },
  selectColorCon: {
    flexDirection: 'row',
  },
  colorArea: {
    width: SW(6),
    height: SW(6),
    backgroundColor: COLORS.bluish_green,
    borderRadius: 5,
    marginRight: 3,
  },
  scrollableBodyCon: {
    width: windowWidth * 0.48,
    alignSelf: 'center',
    // height: windowHeight * 0.45,
    flexDirection: 'row',
  },
  colorSelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.09,
    alignItems: 'center',
    borderEndWidth: 1,
    borderColor: COLORS.solidGrey,
  },
  quantitySelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.25,
    paddingHorizontal: moderateScale(10),
  },
  RemindSelectArea: {
    // height: windowHeight * 0.45,
    width: windowWidth * 0.14,
  },
  imageView: {
    borderWidth: 2,
    borderRadius: 5,
    width: SW(25),
    height: SW(25),
    marginVertical: verticalScale(3),
  },
  scrollImage: {
    width: SW(23),
    height: SW(23),
    resizeMode: 'contain',
  },
  sizeSelectItemCon: {
    height: SW(11),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: moderateScale(10),

    marginTop: 7,
  },
  adminItemCon: {
    height: SW(11),
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(10),

    marginTop: 7,
  },
  bell: {
    width: SW(7),
    height: SW(7),
    resizeMode: 'contain',
    marginHorizontal: moderateScale(4),
  },
  sizeSelectItemCona: {
    borderWidth: 1,
    borderColor: COLORS.solidGrey,
    borderRadius: 5,
    paddingHorizontal: moderateScale(10),
  },

  // addto cart detail modal css start

  blueListHeader: {
    backgroundColor: COLORS.primary,
    height: SH(40),
    borderRadius: 5,
    justifyContent: 'center',
    // alignContent: 'center',
  },

  tableListSide: {
    width: windowWidth * 0.25,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  listLeft: {
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  cashLabelWhite: {
    color: COLORS.white,
    fontSize: SF(14),
    fontFamily: Fonts.Medium,
  },
  cashLabelWhiteHash: {
    paddingHorizontal: moderateScale(15),
  },
  tableListSide: {
    width: windowWidth * 0.25,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },

  tableListSide2: {
    width: windowWidth * 0.29,
    paddingRight: 20,
    alignItems: 'center',
  },
  blueListData: {
    borderWidth: 1,
    height: SH(48),
    borderRadius: 5,
    borderColor: COLORS.solidGrey,
    justifyContent: 'center',
    marginVertical: verticalScale(4),
    // alignContent: 'center',
  },
  blueListDataText: {
    color: COLORS.solid_grey,
    fontSize: SF(13),
    fontFamily: Fonts.Regular,
  },
  columbiaMen: {
    width: SW(6),
    height: SW(6),
    resizeMode: 'contain',
  },
  minus: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
  },
  sukNumber: {
    color: COLORS.darkGray,
    fontSize: SF(11),
    fontFamily: Fonts.Regular,
  },
  listCountCon: {
    borderWidth: 1,
    width: SW(30),
    height: SH(30),
    borderRadius: 3,
    borderColor: COLORS.solidGrey,
    // paddingVertical: verticalScale(1),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: moderateScale(4),
    alignItems: 'center',
  },
  borderCross: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
  },
  _subTotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
  },
  _substotalTile: {
    color: COLORS.black,
    fontFamily: Fonts.Regular,
    fontSize: ms(5.5),
    marginTop: ms(5),
  },
  _subTotalPrice: {
    color: COLORS.solid_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(5.5),
    marginTop: ms(7),
  },
  _horizontalLine: {
    height: ms(1),
    width: '90%',
    marginTop: ms(4),
    backgroundColor: COLORS.textInputBackground,
  },

  _paymentTitleContainer: {
    marginTop: ms(10),
    flexDirection: 'row',
    alignSelf: 'flex-start',
    marginLeft: ms(15),
  },
  _payTitle: {
    fontSize: ms(7),
    fontFamily: Fonts.Regular,
    color: COLORS.dark_grey,
  },
  _paySubTitle: {
    fontSize: ms(7),
    fontFamily: Fonts.SemiBold,
    color: COLORS.solid_grey,
  },
  _commonPayTitle: {
    alignSelf: 'flex-start',
    marginLeft: ms(15),
    marginTop: ms(3),
    fontSize: ms(7),
    color: COLORS.black,
    fontFamily: Fonts.Regular,
  },
  _upperContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    flex: 1,
  },
  _kUpperContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  _kContainer: {
    height: ms(200),
    width: ms(300),
    backgroundColor: COLORS.textInputBackground,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: ms(5),
  },
  _kCenterContainer: {
    height: '100%',
    alignSelf: 'flex-end',
    flex: 0.6,
    borderLeftWidth: 1,
    borderColor: COLORS.textInputBackground,
    alignItems: 'center',
  },
  _kSubCenterContainer: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    marginTop: ms(5),
  },
  _kAddress: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    marginTop: ms(5),
  },
  _kNumber: {
    color: COLORS.dark_grey,
    fontFamily: Fonts.Regular,
    fontSize: ms(6),
    marginTop: ms(3),
  },
  _flatListContainer: { height: ms(100), width: '100%', marginTop: ms(5) },
  _barCode: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(10),
    color: COLORS.dark_grey,
  },
  _barCodeImage: { height: ms(25), width: '70%', marginTop: ms(5) },
  _thankyou: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(11),
    color: COLORS.dark_grey,
    marginTop: ms(10),
  },
  _cashRemainView: {
    marginTop: ms(15),
    height: 1,
    width: '50%',
    backgroundColor: COLORS.silver_solid,
  },
  _cashRemainText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(15),
    color: COLORS.solid_grey,
    marginTop: ms(10),
  },
  _printButton: {
    width: '30%',
    height: ms(26),
    backgroundColor: 'transparent',
    borderColor: COLORS.lineGrey,
    borderWidth: 0.2,
    borderRadius: ms(1),
    marginHorizontal: moderateScale(5),
  },
  _printBtnText: {
    fontFamily: Fonts.SemiBold,
    fontSize: ms(7),
    color: COLORS.darkGray,
    fontWeight: 'normal',
  },
  noProductText: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: verticalScale(50),
  },
  emptyListText: {
    fontSize: SF(16),
    color: COLORS.primary,
    fontFamily: Fonts.Regular,
  },
  productListHeight: {
    // borderWidth: 1,
    height: windowHeight * 0.7,
  },
  loader: {
    position: 'absolute',
    alignSelf: 'center',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  addNotesCon: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: windowWidth * 0.35,
    height: windowHeight * 0.45,
    // position: 'absolute',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: moderateScale(13),
  },
  addNotesCon2: {
    paddingHorizontal: moderateScale(8),
  },
  addDiscountConPop: {
    height: windowHeight * 0.55,
  },
  addNotesInput: {
    backgroundColor: COLORS.textInputBackground,
    borderRadius: 5,
    height: windowHeight * 0.27,
    textAlignVertical: 'top',
    borderColor: COLORS.solidGrey,
    borderWidth: 1,
    paddingHorizontal: moderateScale(10),
  },
  addNotes: {
    fontSize: SF(14),
    color: COLORS.solid_grey,
    fontFamily: Fonts.Medium,
  },
  backProScreen: {
    backgroundColor: COLORS.washGrey,
    width: SW(65),
    borderRadius: 5,
    height: SH(45),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowStyle: {
    width: SW(5),
    height: SW(5),
    resizeMode: 'contain',
    tintColor: COLORS.solid_grey,
    transform: [{ rotate: '180deg' }],
  },
  iconStyle: {
    width: SW(8),
    height: SW(8),
    resizeMode: 'contain',
    borderRadius: 100,
    marginRight: ms(3),
  },
  _blueButton: {
    backgroundColor: COLORS.primary,
    height: ms(40),
    width: '98%',
    marginTop: ms(10),
    color: COLORS.white,
  },
});
