export const NAVIGATION = {
  home: 'Home',
  login: 'Login',
  profile: 'Profile',
  verifyPhone: 'VerifyPhone',
  verifyOtp: 'VerifyOtp',
  merchantPasscode: 'MerchantPasscode',
  loginIntial: 'LoginIntial',
  retails: 'Retails',
  deliveryOrder: 'DeliveryOrder',
  shippingOrder: 'ShippingOrder',
  wallet: 'Wallet',
  management: 'Management',
  customers: 'Customers',
  calender: 'Calender',
  analytics: 'Analytics',
  verifySucess: 'VerifySucess',
  reward: 'Reward',
  setting: 'Setting',
  dashBoard: 'DashBoard',
  posUsers: 'POSUsers',
  products: 'Products',
  posUserPasscode: 'PosUserPasscode',
  posRetail: 'PosRetail',
  CartAmountTips: 'CartAmountTips',
};
