export const STATUS = {
  ERROR: 'ERROR',
  LOADING: 'LOADING',
  NOT_STARTED: 'NOT_STARTED',
  SUCCESS: 'SUCCESS',
};

export const APPOINTMENT_STATUS = {
  REVIEWING: '0',
  ACCEPTED_BY_SELLER: '1',
  COMPLETED: '2',
  REJECTED_BY_SELLER: '3',
};
