export const TYPES = {
    GET_DRAWER_SESSION_REQUEST:'GET_DRAWER_SESSION_REQUEST',
    GET_DRAWER_SESSION_SUCCESS:'GET_DRAWER_SESSION_SUCCESS',
    GET_DRAWER_SESSION_ERROR:'GET_DRAWER_SESSION_ERROR',
    GET_DRAWER_SESSION:'GET_DRAWER_SESSION',
    TRACK_SESSION_SAVE_REQUEST:'TRACK_SESSION_SAVE_REQUEST',
    TRACK_SESSION_SAVE_SUCCESS:'TRACK_SESSION_SAVE_SUCCESS',
    TRACK_SESSION_SAVE_ERROR:'TRACK_SESSION_SAVE_ERROR',
    TRACK_SESSION_SAVE:'TRACK_SESSION_SAVE',
    GET_SESSION_HISTORY_REQUEST:'GET_SESSION_HISTORY_REQUEST',
    GET_SESSION_HISTORY_SUCCESS:'GET_SESSION_HISTORY_SUCCESS',
    GET_SESSION_HISTORY_ERROR:'GET_SESSION_HISTORY_ERROR',
    GET_SESSION_HISTORY_RESET:'GET_SESSION_HISTORY_RESET',
    GET_SESSION_HISTORY:'GET_SESSION_HISTORY',
    END_TRACKING_REQUEST :'END_TRACKING_REQUEST',
    END_TRACKING_SUCCESS:'END_TRACKING_SUCCESS',
    END_TRACKING_ERROR:'END_TRACKING_ERROR',
    END_TRACKING:'END_TRACKING',
    GET_SESSION_BYID_REQUEST:'GET_SESSION_BYID_REQUEST',
    GET_SESSION_BYID_SUCCESS:'GET_SESSION_BYID_SUCCESS',
    GET_SESSION_BYID_ERROR:'GET_SESSION_BYID_ERROR',
    GET_SESSION_BYID:'GET_SESSION_BYID'


  
    


};