export const TYPES = {
    GET_USER_ORDER_REQUEST:'GET_USER_ORDER_REQUEST',
    GET_USER_ORDER_SUCCESS:'GET_USER_ORDER_SUCCESS',
    GET_USER_ORDER_ERROR:'GET_USER_ORDER_ERROR',
    GET_USER_ORDER:'GET_USER_ORDER',
    GET_USER_ORDER_RESET:'GET_USER_ORDER_RESET',
    GET_ORDER_USER_REQUEST:'GET_ORDER_USER_REQUEST',
    GET_ORDER_USER_SUCCESS:'GET_ORDER_USER_SUCCESS',
    GET_ORDER_USER_ERROR:'GET_ORDER_USER_ERROR',
    GET_ORDER_USER_RESET:'GET_ORDER_USER_RESET',
    GET_ORDER_USER:'GET_ORDER_USER',
    GET_CUSTOMERS_REQUEST:'GET_CUSTOMERS_REQUEST',
    GET_CUSTOMERS_SUCCESS:'GET_CUSTOMERS_SUCCESS',
    GET_CUSTOMERS_ERROR:'GET_CUSTOMERS_ERROR',
    GET_CUSTOMERS:'GET_CUSTOMERS'
};