export const TYPES = {
  GET_ORDER_DELIVERIES_REQUEST: 'GET_ORDER_DELIVERIES_REQUEST',
  GET_ORDER_DELIVERIES_SUCCESS: 'GET_ORDER_DELIVERIES_SUCCESS',
  GET_ORDER_DELIVERIES_ERROR: 'GET_ORDER_DELIVERIES_ERROR',
  GET_ORDER_DELIVERIES_RESET: 'GET_ORDER_DELIVERIES_RESET',
  GET_ORDER_DELIVERIES: 'GET_ORDER_DELIVERIES',

  GET_DRAWER_SESSION_REQUEST: 'GET_DRAWER_SESSION_REQUEST',
  GET_DRAWER_SESSION_SUCCESS: 'GET_DRAWER_SESSION_SUCCESS',
  GET_DRAWER_SESSION_ERROR: 'GET_DRAWER_SESSION_ERROR',
  GET_DRAWER_SESSION_RESET: 'GET_DRAWER_SESSION_RESET',
  GET_DRAWER_SESSION: 'GET_DRAWER_SESSION',

  GET_DRAWER_SESSION_POST_REQUEST: 'GET_DRAWER_SESSION_POST_REQUEST',
  GET_DRAWER_SESSION_POST_SUCCESS: 'GET_DRAWER_SESSION_POST_SUCCESS',
  GET_DRAWER_SESSION_POST_ERROR: 'GET_DRAWER_SESSION_POST_ERROR',
  GET_DRAWER_SESSION_POST_RESET: 'GET_DRAWER_SESSION_POST_RESET',
  GET_DRAWER_SESSION_POST: 'GET_DRAWER_SESSION_POST',

  START_TRACKING_SESSION_REQUEST: 'START_TRACKING_SESSION_REQUEST',
  START_TRACKING_SESSION_SUCCESS: 'START_TRACKING_SESSION_SUCCESS',
  START_TRACKING_SESSION_ERROR: 'START_TRACKING_SESSION_ERROR',
  START_TRACKING_SESSION: 'START_TRACKING_SESSION',

  GET_TOTAL_SALE_REQUEST: 'GET_TOTAL_SALE_REQUEST',
  GET_TOTAL_SALE_SUCCESS: 'GET_TOTAL_SALE_SUCCESS',
  GET_TOTAL_SALE_ERROR: 'GET_TOTAL_SALE_ERROR',
  GET_TOTAL_SALE_RESET: 'GET_TOTAL_SALE_RESET',
  GET_TOTAL_SALE: 'GET_TOTAL_SALE',

  POS_LOGIN_DETAIL_REQUEST: 'POS_LOGIN_DETAIL_REQUEST',
  POS_LOGIN_DETAIL_SUCCESS: 'POS_LOGIN_DETAIL_SUCCESS',
  POS_LOGIN_DETAIL_ERROR: 'POS_LOGIN_DETAIL_ERROR',
  POS_LOGIN_DETAIL_RESET: 'POS_LOGIN_DETAIL_RESET',
  POS_LOGIN_DETAIL: 'POS_LOGIN_DETAIL',

  SEARCH_PRODUCT_LIST_REQUEST: 'SEARCH_PRODUCT_LIST_REQUEST',
  SEARCH_PRODUCT_LIST_SUCCESS: 'SEARCH_PRODUCT_LIST_SUCCESS',
  SEARCH_PRODUCT_LIST_ERROR: 'SEARCH_PRODUCT_LIST_ERROR',
  SEARCH_PRODUCT_LIST_RESET: 'SEARCH_PRODUCT_LIST_RESET',
  SEARCH_PRODUCT_LIST: 'SEARCH_PRODUCT_LIST',
};
