export const TYPES = {
  // Graph Types
  GET_REWARD_GRAPH_REQUEST: 'GET_REWARD_GRAPH_REQUEST',
  GET_REWARD_GRAPH_SUCCESS: 'GET_REWARD_GRAPH_SUCCESS',
  GET_REWARD_GRAPH_ERROR: 'GET_REWARD_GRAPH_ERROR',
  GET_REWARD_GRAPH_RESET: 'GET_REWARD_GRAPH_RESET',
  GET_REWARD_GRAPH: 'GET_REWARD_GRAPH',

  // Rewarded Users Types
  GET_REWARDED_USERS_REQUEST: 'GET_REWARDED_USERS_REQUEST',
  GET_REWARDED_USERS_SUCCESS: 'GET_REWARDED_USERS_SUCCESS',
  GET_REWARDED_USERS_ERROR: 'GET_REWARDED_USERS_ERROR',
  GET_REWARDED_USERS_RESET: 'GET_REWARDED_USERS_RESET',
  GET_REWARDED_USERS: 'GET_REWARDED_USERS',

  // GET USER REWARD
  GET_REWARD_USER_REQUEST: 'GET_REWARD_USER_REQUEST',
  GET_REWARD_USER_SUCCESS: 'GET_REWARD_USER_SUCCESS',
  GET_REWARD_USER_ERROR: 'GET_REWARD_USER_ERROR',
  GET_REWARD_USER_RESET: 'GET_REWARD_USER_RESET',
  GET_REWARD_USER: 'GET_REWARD_USER',
};
