export const TYPES = {
  GET_TOTAL_TRA_REQUEST:'GET_TOTAL_TRA_REQUEST',
  GET_TOTAL_TRA_SUCCESS:'GET_TOTAL_TRA_SUCCESS',
  GET_TOTAL_TRA_ERROR:'GET_TOTAL_TRA_ERROR',
  GET_TOTAL_TRA_RESET:'GET_TOTAL_TRA_RESET',
  GET_TOTAL_TRA:'GET_TOTAL_TRA',

  GET_TOTAL_TRA_DETAIL_REQUEST:'GET_TOTAL_TRA_DETAIL_REQUEST',
  GET_TOTAL_TRA_DETAIL_SUCCESS:'GET_TOTAL_TRA_DETAIL_SUCCESS',
  GET_TOTAL_TRA_DETAIL_ERROR:'GET_TOTAL_TRA_DETAIL_ERROR',
  GET_TOTAL_TRA_DETAIL_RESET:'GET_TOTAL_TRA_DETAIL_RESET',
  GET_TOTAL_TRA_DETAIL:'GET_TOTAL_TRA_DETAIL',

  GET_TOTAL_TRA_TYPE_REQUEST:'GET_TOTAL_TRA_TYPE_REQUEST',
  GET_TOTAL_TRA_TYPE_SUCCESS:'GET_TOTAL_TRA_TYPE_SUCCESS',
  GET_TOTAL_TRA_TYPE_ERROR:'GET_TOTAL_TRA_TYPE_ERROR',
  GET_TOTAL_TRA_TYPE_RESET:'GET_TOTAL_TRA_TYPE_RESET',
  GET_TOTAL_TRA_TYPE:'GET_TOTAL_TRA_TYPE'
  };