export const en = {
  common: {
    loading: 'Loading',
    connectionError: 'Connection error',
  },
  home: {
    header: 'Home',
    message: 'Welcome',
    variant: 'App variant: ',
  },
  login: {
    username: 'Username',
    usernameHint: 'Enter your username',
    button: 'Login',
    password: 'Password',
    passwordHint: 'Enter your password',
    invalidCredentials: 'Invalid Username/Password',
  },
  profile: {
    header: 'Profile',
    logout: 'Logout',
    message: 'This screen has the iOS native large header.',
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',

    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID:256913',
    date: 'Today Wednesday 11 Aug 2022',
    time: 'Time 3:25 pm',
  },
  deliveryOrders: {
    heading: 'Delivery orders',
    search: 'Search',
    orderNumber: 'Number of Orders',
    orderReview: 'Orders to review',
    viewAll: 'View all',
    orderConversion: 'Order conversion',
    deliveryOrders: 'Delivery Orders',
    back: 'Back',
    orderId: 'Order#',
    orderDate: 'August 30, 2022',
    name: 'Rebecca R. Russell',
    address: '1480 Bassel Street, New Orleans, LA 70113',
    deliveryType: 'Express Delivery',
    time: 'Immediately',
    ordersPreparing: 'Orders Preparing',
    ready: 'Ready for Pickup',
    subTotal: 'Sub Total',
    subTotalValue: '$4.00',
    discount: 'Discount',
    discountValue: '-$2.00',
    tax: 'Tax',
    total: 'Total',
    totalValue: '$254.60',
    items: 'Items',
    readyButton: 'Ready for Pickup',
    decline: 'Decline',
    accept: 'Accept Order',
    profileName: 'John Mike',
    distance: '5.69 miles away',
    orderStatus: 'Order status',
    assignedDriver: 'Assigned driver',
    delivery: 'Delivery',
    pickup: 'Product Pickup',
    nextTo: 'Next to your block',
    assign: 'Assign Driver',
    orderAccepted: 'Order accepted',
    orderOfReview: 'Order review',
    readyToPickup: 'Ready to pickup',
    within: 'with in 10 minutes',
    dateTime: '21 Jun, 2022  |   10:30 am',
    verifyCode: 'Verify code',
    verifyCode: 'Verify code',
    selectShip: 'Select shipping',
    shippingOrder: 'Shipping orders',
    shipPtr: 'Pickup by SHIP PTNR SITE USPS AWAITS ITEM',
    imperialAdd: 'IMPERIAL, PA, 15126, US • Aug 5, 2:39am',
    delivered: 'Delivered',
    verifySuccess: 'Verifiered successfull',
    orderView: 'Orders to review',
    orderPrepare: 'Order Preparing',
    readyPickup: 'Ready to pickup',
    cancelled: 'Cancelled',
    acceptSeller: 'Accept By Seller',
    assignToDriver: 'Assign to Driver',
    pickup: 'Pickup',
    orderReject: 'Order rejected',
  },
  verifyPhone: {
    heading: 'Verify your phone number',
    subHeading: 'Please enter your number to phone number',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  posUsersList: {
    heading: 'To use the POS Login',
    logOut: 'Log Out',
  },
  verifyOtp: {
    heading: 'Verify your phone number',
    subHeading: 'Enter OTP code here',
    placeHolderText: '815-288-0329',
    button: 'Continue',
  },
  passcode: {
    heading: 'Enter Passcode',
    success: 'Successfully verified',
    loginBack:
      'Please login back to your email inbox and set your new password',
  },
  loginIntial: {
    heading: 'CONFIRM YOUR LOG IN',
    name: 'Millicent C. Edward',
    id: 'ID : ',
    date: 'Today',
    time: 'Time ',
  },
  retail: {
    numpadButton: '123',
    clearCart: 'Clear cart',
    moreAction: 'More action',
    subTotal: 'Sub Total',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    items: 'Items',
    checkOut: 'Checkout',
    price: 'Price',
    bundleOffer: 'Bundle offer',
    removecart: 'Remove from cart',
    updateCart: 'Update to cart',
    addDiscount: 'Add Discount',
    addNotes: 'Add Notes',
    addDiscountTocart: 'Add discount to cart',
    notes: 'Notes',
    saveNotes: 'Save notes',
    writeNoteHere: 'Write notes here',
    continue: 'Continue',
    box: 'Box',
    paymentDetail: 'Payment Details',
    payable: 'Payable $',
    tips: 'Tips $',
    cash: 'Cash',
    customer: 'Customer',
    searchProduct: 'Search product here',
    addTocart: '   Add to cart',
    amountDis: 'Amount Discount',
    perDis: 'Percentage Discount',
    DisCode: 'Discount Code',
    DisTitle: 'Discount Title',
    sendRequest: 'Send Request',
    next: 'Next',
  },
  posSale: {
    paymentHeader: 'Customer & Payment',
    walletId: 'Wallet Id',
    scanText: 'or Scan',
    rederecting: 'Redirecting',
    listOfItem: 'List of items',
    rewardpoint: 'Reward Points : 500',
    onex: '1',
    price: '$382.75',
    onlyx: 'x',
    notes: 'Notes:',
    itMynday: 'Its for my birthday!',
    paymentdetail: 'Payment Details',
    paymenttdone: 'Payment Done!',
    Customer: 'Customer',
    customerNo: 'Customer phone number',
    customerName: 'Terry Moore',
    customerMobileNo: '803-238-2630',
    customerEmail: 'harryrady@jourrapide.com',
    customerAddr: '4849 Owagner Lane',
    customerAddr2: 'Seattle, WA 98101',
    customerTotalAmountHeader: 'Total amount: $',
    paid: 'Paid: $',
    tips: 'Tips',
    noTips: 'No Tips',
    cashRecive: 'Cash amount received',
    otherAmount: 'Other amount',
    changeDue: 'Change Due: $',
    firstName: 'First name',
    subCategory: 'Sub-Category',
    category: 'Category',
    discount: 'Discount',
    updateprice: 'Update price',
    addNewProduct: 'Add new product',
    barcode: 'Barcode',
    scanBarcode: 'Scanned Barcode',
    productName: 'Product Name',
    selectCat: 'Select Category',
    selectSubCat: 'Select Sub-category',
    selectBrand: 'Select Brand',
    removeCart: 'Remove from cart',
    updateCart: 'Update to cart',
    sellingPrice: 'Selling Price',
    inventryItem: 'Track Inventory for this item',
    inventryOpen: 'Inventory-Opening',
    inventryRenderPoint: 'Inventory-Reorder Point',
    pack: 'Pack',
    brand: 'Brands',
    stock: ' in stock',
    location: 'Available in another location',
    addToCart: 'Add to cart',
    back: 'Back',
    details: 'Details',
    cartAlraedyEmpty: 'Your cart is currently empty',
    saveDiscount: 'Save Discount',
    pleaseAddNotes: 'Please add notes',
    discountType: 'Please select discount type',
    enterfield: 'Please enter field',
    addItemCart: 'Please item add in the cart',
    selectDisTitle: 'Please select discount title',
    availableStock: 'Available in stock: ',
    viewDetail: 'View details',
    CusNotInSystem: 'Customer not in system',
    lastname: 'Last name',
    emailAdd: 'Email address',
  },

  management: {
    cashTracking: 'Cash Tracking',
    cashDrawer: 'Cash Drawer',
    drawerID: 'Drawer ID:',
    drawerID2: 'Drawer ID: 2',
    session: 'Start tracking session',
    sessionHistory: 'Session history',
    countCash: 'Count cash in drawer',
    amountCounted: 'Amount counted (USD)',
    amount: '$ 0.00',
    note: 'Note',
    save: 'Save',
    viewSession: 'View session',
    date: 'Today Friday Auguest 26, 2022   | 11.04 AM',
    usd: 'USD $',
    expected: 'Expected cash balance',
    addCash: 'Add Cash',
    removeCash: 'Remove Cash',
    cashPayments: 'All Cash Payments',
    totalCashIn: 'Total Cash In',
    totalCashOut: 'Total Cash Out',
    netPayment: 'Net Payment',
    endSession: 'End Session',
    amountAdded: 'Enter amount added',
    amountRemoved: 'Enter amount removed',
    cashAmount: 'Cash amount (USD)',
    confirm: 'Confirm',
    endTrackingSession: 'End tracking session',
    next: 'Next',
    summary: 'Summary',
    allCash: 'All Cash Payments',
    totalCashIn: 'Total Cash In',
    totalCash: 'USD $',
    netPayment: 'Net Payment',
    cashActivity: 'Cash activity',
    endTrackingSessions: 'Ended tracking session',
    leftDrawer: 'Amount left in drawer : USD $0.00',
    dateTime: 'Today Friday Auguest 26, 2022   | 11.04 AM',
    allein: 'Allein',
    removeCash: 'Removed cash',
    countCash: 'Counted Cash',
    discrepancy: 'Discrepancy',
    breakFast: 'Note: breakfast',
    startTrackingSession: 'Stared tracking session',
    amountCount: 'Amount counted : USD $0.00',
    sendEmailButton: 'Send to email',
    manual: 'Manual',
    deliveryCharge: 'Delivery Charge',
    shippingCharge: 'Shipping Charge',
    refund: 'Refund',
    manual: 'Manual',
    removeusd: '-USD $',
    sessionHistory: 'Session history',
    cashSummary: 'Cash summary',
    amountexpect: 'Amount expected',
    amountCounted: 'Amount counted',
    selectAmountDra: 'Select amount to leave in drawer',
    otherAmountusd: 'Other amount (USD)',
    transactionType: 'Transaction type',
  },
  customers: {
    sales: 'Sales',
    totalCustomer: 'Total Customers',
    users: 'Users',
    userprofile: 'User Profile',
    Edit: 'Edit',
    angela: 'Angela K. Loving',
    phoneNumber: '4703-515-1193',
    email: 'vidal.webe2@gmail.com',
    address: '4318 Daffodil Lane, Savage, Virginia(VA), 20763',
    point: 'Points: 2',
    acceptMarket: 'Accept Marketing',
    costo: 'Costco Wholesale',
    costoAdd: '1189 Main Street, Seattle, WA 98161',
    detail: 'Details',
    orderStatus: 'Order status',
    assignDriver: 'Assinging driver',
    verifyCode: 'Verify code',
    waitMinute: 'with in 10 minutes',
    delivery: 'Delivery',
    yourBlock: 'Next to your block',
    productPick: 'Product Pickup',
    assignDriver: 'Assinging driver',
    readyPickup: 'Ready to pickup',
    orderPrepare: 'Order prepare',
    orderAccepted: 'Order accepted',
    dateTime: '21 Jun, 2022  |   10:30 am',
    carriar: 'Carriar:',
    geredo: 'Gerardo K. Jennings',
    contact: 'Contact',
    customer: 'Customers',
    showResult: 'Showing Results',
    completed: 'Completed',
    userdetail: 'User details',
    orderReview: 'Order review',
  },
  trackingNumber: {
    trackingNo: 'Tracking Number# 7409309398BCEE',
  },
  calender: {
    calender: 'Calender',
    requestFor: 'Request for',
    hairCut: 'Haircut',
    timeLabel: 'Time:',
    time: '10.00 AM- 11.00 PM',
    dateLabel: 'Date:',
    date: 'Sunday, Oct 29, 2022',

    no: 'No',
    addr: '1189 Main Street, Seattle, WA 98161',
    email: 'richard@example.com',
    scheduledetails: 'Schedule details',
    appointment: 'Appointment Details',
    service: 'Service',
    apt: '#APT0001',
    upcoming: 'Upcoming',
    aptDate: '21 Oct 2019 10:00 AM',
    conform: 'Confirm Date:',
    paidAmount: 'Paid Amount',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    accept: 'Accept',
    decline: 'Decline',
    approve: 'Approve',
    approved: 'Accepted',
    no: 'No',
    cancel: 'Cancel',
  },
  analytics: {
    header: 'Analytics',
    totalProducts: 'Total Products',
    // totalProductsCount: '20,590',
    productDetails: 'Product details',
    totalActiveProduct: 'Total active Products ',
    totalInvetry: 'Total Inventory  Cost',
    activeItem: 'Active Items',
    invetryDetail: 'Inventory Details',
    category: 'Category:',
    tobacco: 'Tobacco',
    edit: 'Edit',
    marboloRed: 'Marlboro Red-Pack',
    detail: 'Details',
    save: 'Save',
    invoiveId: 'Invoice id: 12154NBG',
    print: 'Print',
    supplierDetails: 'Supplier details:',
    supplierAdd: '623 Dorian Row Suite 435',
    supplierNewAdd: 'New Olliehaven',
    streetNo: 'Delaware 747-463',
    city: 'Singapore',
    supplierPhoneNumber: 'Phone: 890-941-8897 x44780',
    trackId: 'Track Id',
    dueDate: 'Due Date',
    date: 'Date',
    taxNumberLabel: 'Tax Number:',
    taxNumber: '215698494946545131',
    FedEx: 'FedEx',
    subtotal: 'Sub Total',
    discount: 'Discount',
    shippingCharge: 'Shipping Charge',
    commision: 'Commission (10%)',
    discountPrice: '$25.00',
    comisionCharge: '$100.00',
    orderHeaader: 'Order# 25659165659165',
    complete: 'Completed',
    walletId: '509 236 2365',
    walletIdLabel: 'Wallet Id',
    returnShipingDetail: 'Return Shipping Details',
    ups: 'UPS',
    share: 'Share',
    refund: '$255.00',
    sales: 'Sales',
    totalRevenue: 'Total Revenue',
    totalRevenueCount: '$6,920,590',
    totalOrder: 'Total Order',
    totalRevenue: 'Total Revenue',
    totalPrice: '$458,041',
    all: 'All',
    onlineSale: 'Online sales',
    storeSale: 'Store sales',
    jbr: 'JBR',
    cash: 'Cash',
    card: 'Card',
    totalOrder: 'Total Order',
    totalOrderCount: '906',
    storeOrder: 'Store Order',
    deliveryOrder: 'Delivery Order',
    shipingOrder: 'Shipping Order',
    noProduct: 'No product found',
  },

  TotalProSub: {
    newAdd: 'New added',
    totalActive: 'Total active',
    discontinued: 'Discontinued',
    lowStock: 'Low stock items',
    itemAdjust: ' Items to be adjusted',
    itemShipped: 'Items to be shipped',
  },
  shipingOrder: {
    shipingRate: '$11.50',
    priorityMalling: 'Priority Mailing services',
    dayShiping: '1-3 days shipping',
    printText: 'Select & Continue to print',
    orderOfReview: 'Orders to review',
    readyToShip: 'Ready to ship',
    printAgain: 'Print Again',
    outStock: 'Out of stock',
    note: 'Note',
    track: 'Track',
    contact: 'Contact',
    fedEx: 'FedEx',
    fedNumber: '936128',
    ReadyToShip: 'Ready to ship',
    orderShip: 'Order Shipped',
    cancelShip: 'Cancelled Shipped',
  },
  valiadtion: {
    validPhone: 'Please enter valid phone number',
    enterPhone: 'Please enter phone number',
    enterOtp: 'Please enter OTP',
    fiveDigitOtp: 'Please enter five digit OTP',
    validOtp: 'Please enter valid OTP',
    enterPassCode: 'Please enter passcode',
    validPasscode: 'Please enter valid passcode',
    error: 'not found',
    loading: 'loading...',
    phoneNotExist: 'This number does not exist',
    noData: 'No Data',
    noProduct: 'Product not found',
    noCart: 'No cart',
    pleaseSelectSubCat: 'First select sub-category',
    pleaseEnterFirstName: 'Please enter first name',
    pleaseEnterPH: 'Please enter phone number',
    pleaseEnterLastName: 'Please enter last name',
    pleaseEnterEmail: 'Please enter Email',
    validEmail: 'Please enter valid email',
    ordernotfound: 'Order not found',
    completeStep: 'Please complete the wallet step',
  },
  successMessages: {
    loginSuccess: 'Login succesfully',
  },
  reward: {
    totalReward: 'Total Rewards',
    jobrCountLabel: 'JOBR',
    first: '1',
    st: 'st',
    second: '2',
    nd: 'nd',
    third: '3',
    rd: 'rd',
    viewAll: 'View all',
    rewards: 'Rewards',
  },
  settings: {
    security: 'Security',
    twoStepVerifiCon: '2-step verification',
    securitysubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    memeberEnable: 'Team members must enable their own verification methods.',
    teamMemeber: '2-step verification for team members',
    enableSecurity: 'Enable Two-Steps Security',
    firstDownloader: 'First, download Google Authenticator from the ',
    googleAuth: 'Google authenticator',
    instead:
      'Instead of waiting for text messages, get verification codes from an authenticator app. It works even if your phone is offline.',
    doLater: 'I will do it later',
    next: 'Next',
    qrCode: 'Scan QR Code to active  google authenticator',
    device: 'Devices',
    configure: 'Configure Settings on Your Device',
    manageDevice:
      'All you need to manage Basic Point of Sale is a device nickname and location to allow team members to accept payments.',
    barScan: 'Barcode Scanner ',
    oneBlueTToth: '1 bluetooth device active',
    addNew: 'Add New',
    addbarcode: 'Add Barcode Scanner',
    pluginFirst: '1.  Plugin USB/C Port to  POS Monitor',
    pluginSecond: '2. Scan Barcode Below',
    codeAppear: 'Codes will appear here ',
    done: 'Done',
    addBlueToothHead: 'Add Bluetooth Barcode Scanner',
    searchForDevice: 'Searching for the devices....',
    foundOneDev: 'Found 1 device',
    location: 'Locations',
    businessLocation: 'Business locations',
    locationsubhead:
      'An extra layer to boost your team members account security. A verification code will be required in addition to password each time you sign in.',
    plans: 'Plans',
    yourPlan: 'Your Plan',
    basic: 'Basic',
    everyThingNeed:
      'Everything you need to create a store, ship products, and process payments',
    chnagePlan: 'Change Plan',
    includePlan: 'Your Plan includes app',
    planFeat: 'Plan Features',
    paymentMethod: 'Payment method',
    planFit: 'Plan that fits your scale',
    simpleTra: 'Simple, Transparent pricing that grows with you',
    monthlyBil: 'Monthly Billing',
    annualBil: 'Annually Billing',
    basicSubHead:
      'Everything you need to create a store, ship products, and process payments',
    getStart: 'Get Started',
    invoice: 'Invoices',
    invoiveHeading: 'Taxes and duties',
    invoiveSubHeading:
      'Add a curbside, drive-through, or in-store pickup. Specify your business hours, the pickup location, and add a brief instruction on how the pickup works for customers.',
    smshead: 'Sms to phone number ',
    smsSubHead: 'It may apply charge ',
    printHead: 'Print invoice',
    printSubHead: 'Needs to connect printer for print invoice',
    emailHead: 'Email',
    emailSubHead: 'Email will Send to buyersi email address',
    invoiceTemplate: 'Invoice Template',
    publishDate: 'Publish date:',
    date: 'Sep 27, 2023 10: 00 AM',
    activate: 'Activate:',
    taxHead: 'Taxes and duties',
    taxSubHead:
      'If you haven’t already, create a shipping zone in the region(s) you’re liable in. Then, find the region in this list and select it to manage its tax settings. If you’re unsure about where you’re liable, check with a tax professional.',
    taxes: 'Taxes',
    active: 'Active',
    selectHead: 'Select your Operating Country',
    country: 'Country',
    cancel: 'Cancel',
    next: 'Next',
    selectHeadState: 'Select your Operating States',
    selectState: 'Select States',
    taxPayerHeadl: 'Tax Payer Information',
    name: 'Name',
    ssn: 'SSN or EIN',
    streetAdd: 'Street Address',
    appartement: 'Apartment/Suite',
    verify: 'Verify',
    SSN: 'SSN',
    verified: 'Verified',
    operatingCountry: 'Operating Country',
    activateStateTax: 'Activate your State Tax',
    financialReport: 'This will show in your financial reports.',
    checkoutMore: 'Checkout for more',
    activateBtn: 'Activate',
    addState: 'Add State',
    craeteTax: 'Create tax',
    details: 'Details',
    taxName: 'Tax name',
    taxRate: 'Tax rate',
    location: 'Location',
    taxCalculation: 'Tax calculation',
    includeTax: 'Include tax in item price',
    includetaxSubhead:
      'If tax is included, the tax will appear in your reports, but your customers will not see the tax on their receipt.',
    notApplied: 'Specify when this tax should not be applied.',
    addRule: 'Add exemption rule',
    save: 'Save',
    taxexmption: 'Tax exemption name',
    exempttax: 'Exempt tax',
    amount: 'Amount',
    refundPolicy: 'Refund policy',
    introduction: 'Introduction',
    notification: 'Notifications',
    addlanguage: 'Add Language',
    businessName: 'Business Name',
  },
  dashboard: {
    todaySale: "Today's Sales",
    cashSaleAmount: 'Cash sales amount',
    cardSaleAmount: 'Card sales amount',
    jobrCoinSaleAmount: 'JOBR Coin sales amount',
    cashDrawer: 'Cash Drawer',
    openBal: 'Opening Balance',
    closeBal: 'Closing Balance',
    logTime: 'log in Time',
    session: 'Session',
    lockScreen: 'Lock screen',
    startSelling: 'START SELLING',
    scanSer: 'Scan/Search',
    deliveries: 'Order Deliveries',
    holdCart: 'Hold Cart',
    clearcart: 'Clear cart',
    ok: 'OK',
    totalItem: 'Total Items:',
    yourSessionEnd: 'Your Session Ends',
    expandOneHour: 'Expand 1 hour',
    expandTwoHour: 'Expand 2 hour',
  },
  wallet: {
    config: 'Wallet Config',
    payJBR: 'Pay by JBR Coin',
    system: 'System: Online Shop, POS',
    dafaultPayment: 'Dafault Payment',
    shopifyPayments:
      'You need to proivde some additional information about your business to start receiving payouts from Shopify Payments',
    payCash: 'Pay by Cash',
    systemPOS: 'System: POS',
    sila: 'Sila',
    setupSila: 'Setup Sila',
    cards: 'Cards,Bank tranfer and all',
    silaProtection:
      'Sila is a powerful processor that provides a sealess checkout experience, various payments options, and fraud protection.',
    payBusinesses:
      '.  Pay 2.9% + $0.30 per transaction. Custom rates are available for qualified businesses',
    sellChanges:
      ".  Sell subscription: collect your customers' card  details and charge automatically at a later time, with no additional fees for subscription charges",
    alwaysPayments:
      '.  Always feel secure with advanced fraud protection that automatically blocks high-risk payments',
    byAccount:
      'By enabling payments through Sila, you will be accepting Stripe Services Agreement. Please refer to the list of Prohibited Businesses before registering for and opening a Stripe account',
    silaButton: 'Setup Sila',
    wallet: 'Wallet',
    totalTransections: 'Total Transactions:',
    today: 'Today',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quaterly: 'Quaterly',
    yearly: 'Yearly',
    transationPrice: '$',
    transectionsPrice: '$8,458,041',
    paginationCount: '1-20 of 10,000',
    orderNo: 'Order# ',
    completed: 'Completed',
    PaymentDetails: 'Payment Details',
    buyer: 'Buyer',
    angela: 'Angela K. Loving',
    angelaAddress1: '4156 College View Belleville, IL 62220',
    angelaAddress2: 'Phone:',
    invoiceDetails: 'Invoice details',
    invoiceIdLabel: 'Invoice Id: ',
    createDateLabel: 'Created Date: ',
    dueDateLabel: 'Due Date: ',
    deliveryDate: 'Delivery date: ',
    dueDate: '05-04-2022',
    point: 'Points: 20',
    subtotal: 'Sub-Total',
    serviceCharge: 'Service Charge',
    discount: 'Discount ( MIDApril100)',
    shippingCharge: 'Shipping Charge',
    total: 'Total',
    subtotalPrice: '$7,363.20',
    paid: 'Paid',
    shippingDetail: 'Shipping Details',
    trackingNo: 'Tracking number#  6533284651BC12',
    willis: 'Willis V Burleson',
    delivered: 'Delivered',
    tracking: 'Tracking',
    listOfItem: 'List of items',
    item: 'items',
    rewardPoint: 'Reward Points:',
  },
  shipping: {
    shipping: 'Shipping & Pickups',
    local: 'Local Pickup',
    businessName: 'Business Name',
    address: '1899 Rollins Road , Grand Island Nebraska 68801, United States',
    jobrDelivery: 'JOBR Delivery',
    localOff: 'Local Drop-off',
    shippingText: 'Shipping',
  },

  Languages: {
    languages: 'Languages',
    Publishedlanguages: 'Published languages',
    active:
      "Active in the markets they've been added to and visible to customers.",
    englishUSE: 'English  (USE)',
    englishUK: 'English (UK)',
    default: 'Default',
    addLanguage: 'Add language',
    languagesName: 'Language (7)',
    add: 'Add',
    cancel: 'Cancel',
    spanish: 'Spanish',
  },
  posRetail: {
    categories: 'Categories',
    subCategories: 'Sub Categories',
    brand: 'Brands',
    payNow: 'Pay Now ',
    backProdscreen: 'Back to Product Screen',
  },
  Staff: {
    Staff: 'Staff',
    staffList: 'Staff List',
    staffDes:
      "Active in the markets they've been added to and visible to customers.",
    addStaff: 'Add Staff',
  },
  legal: {
    LegalText: 'Legal',
  },
  Policies: {
    PoliciesText: 'Policies',
  },
  deviceDetails: {
    deviceDetailsText: 'Device Details',
  },
};
